function Structure3DFetcher() {
    // ...
    // this.fetch = function (id, callback) {
    //     // ...
    //     var url = this.url + id;
    //     // ...
    //     var xhr = new XMLHttpRequest();
    //     // ...
    //     xhr.open('GET', url, true);
    //     // ...
    //     xhr.onload = function () {
    //         // ...
    //         var data = JSON.parse(xhr.responseText);
    //         // ...
    //         callback(data);
    //     };
    //     // ...
    //     xhr.send();
    // };
}

export default Structure3DFetcher;